title: Laws of Software
site-img: laws-of-software.jpg
description: A catalog of the laws guiding software development. Especially useful for individual contributors, new managers, and product managers who want to build well-made software.
permalink: ':title/'
baseurl: ""
url: "https://www.laws-of-software.com/"
site-twitter:

# Author Settings
author: Shai Sachs
author-img: shai-sachs.jpg # add your photo
about-author: I am a Staff Engineer at Wayfair. Contact me if you want to join us!
author-firstname: Shai
author-lastname: Sachs
social-home: https://shaisachs.com
social-twitter:
social-facebook: shaisachs
social-github: shaisachs # add your Github handle
social-linkedin: shaisachs
social-email: # add your Email address
social-mastodon: https://mstdn.party/@shaisachs

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

collections:
  laws:
    output: true
  books:
    output: false