title: Laws of Software
site-img: laws-of-software.jpg
description: A catalog of the laws guiding software development. Especially useful for individual contributors, new managers, and product managers who want to build well-made software.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Shai Sachs
author-img: shai-sachs.jpg # add your photo
about-author: I am a Staff Engineer at Wayfair. Contact me if you want to join us!
social-home: https://shaisachs.com
social-twitter: shaisachs
social-facebook: shaisachs
social-github: shaisachs # add your Github handle
social-linkedin: shaisachs
social-email: # add your Email address

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

collections:
  laws:
    output: true